name: Publish Python to PyPI and TestPyPI
on: push

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
       python-version: '3.x'
       architecture: 'x64'

    - name: Install Python packages
      run: python3 -m pip install wheel --user

    - name: Build a binary wheel
      run: python3 setup.py bdist_wheel

    - name: Build a source tarball
      run: python3 setup.py sdist

    - name: Publish distribution ğŸ“¦ to test.pypi.org
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

#    - name: Publish distribution ğŸ“¦ to PyPI
#      if: startsWith(github.event.ref, 'refs/tags')
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        password: ${{ secrets.pypi_password }}

